package postulatum.plantum.plantum.model

import kotlinx.serialization.Serializable

/**
 * A semester is a planning unit. It describes a fictitious semester that has not yet been assigned to a specific half-year.
 */
@Serializable
data class Semester(val id: String, val name: String, val modules: List<Module>) {

    /**
     * Autogenerated.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as Semester

        if (id != other.id) return false
        if (name != other.name) return false
        if (modules != other.modules) return false

        return true
    }

    /**
     * Autogenerated.
     */
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + modules.hashCode()
        return result
    }
}
