package postulatum.plantum.plantum.model

data class Slot(val id: String, val name: String, val term: Term, val year: UInt, val semester: List<Semester>) {

    /**
     * Autogenerated.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as Slot

        if (id != other.id) return false
        if (name != other.name) return false
        if (term != other.term) return false
        if (year != other.year) return false
        if (semester != other.semester) return false

        return true
    }

    /**
     * Autogenerated.
     */
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + term.hashCode()
        result = 31 * result + year.hashCode()
        result = 31 * result + semester.hashCode()
        return result
    }
}
