package postulatum.plantum.plantum.model

import kotlinx.serialization.Serializable

@Serializable
data class Slot(
    val id: String,
    val term: Term,
    val year: UInt,
    val semester: List<Semester>,
    val description: String? = null
) {
    /**
     * Display name generated from term and year.
     * Examples: "WiSe 2024/25", "SoSe 2025"
     */
    val displayName: String
        get() {
            val termStr = when (term) {
                Term.WISE -> "WiSe"
                Term.SOSE -> "SoSe"
            }
            val yearStr = when (term) {
                Term.WISE -> "$year/${(year + 1u).toString().takeLast(2)}"
                Term.SOSE -> year.toString()
            }
            return "$termStr $yearStr"
        }

    /**
     * Autogenerated.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as Slot

        if (id != other.id) return false
        if (term != other.term) return false
        if (year != other.year) return false
        if (semester != other.semester) return false
        if (description != other.description) return false

        return true
    }

    /**
     * Autogenerated.
     */
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + term.hashCode()
        result = 31 * result + year.hashCode()
        result = 31 * result + semester.hashCode()
        result = 31 * result + (description?.hashCode() ?: 0)
        return result
    }
}
